sudo: required
services: 
  - docker

before_install: 
  - docker build -t zavanton/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true zavanton/docker-react npm run test

# deploy:
  # provider: elasticbeanstalk
  # region: "us-east-2"
  # name: "docker"
  # env: "Docker-env"
  # bucket_name: "elasticbeanstalk-us-east-2-565447122202"
  # bucket_path: "docker"
  # on:
  #   branch: master
  #
#




